apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-xnol
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-xnol
    app.kubernetes.io/part-of: build-suite-test-application-hqnz
  name: test-annotations-xnolixyj
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-annotations-xnol
    weight: 100
status: {}
