apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-xnol
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-xnol
    app.kubernetes.io/part-of: build-suite-test-application-hqnz
  name: test-annotations-xnol
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-xnol
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-xnol
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-zhsd-tenant/build-suite-test-application-hqnz/test-annotations-xnol@sha256:61d3a339caa52db87b85901bc664a356dba463fccb0cebc76f466951a8f60203
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
